trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  patch: $[counter('versioncounter', 89)]
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: 1.0.$(patch)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    maximumCpuCount: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
